-- Board schema: profiles, posts, attachments, likes, RLS and safe write RPCs.
create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name varchar(50) not null check (char_length(trim(display_name)) between 1 and 50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.posts (
  id uuid primary key default gen_random_uuid(),
  post_number bigint generated by default as identity unique not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name varchar(50) not null check (char_length(trim(author_name)) between 1 and 50),
  title varchar(200) not null check (char_length(trim(title)) between 1 and 200),
  content text not null check (char_length(trim(content)) > 0),
  password_hash text not null,
  is_secret boolean not null default false,
  like_count integer not null default 0 check (like_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.post_attachments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  original_name text not null check (char_length(trim(original_name)) > 0),
  storage_path text unique not null,
  mime_type varchar(100) not null,
  file_size bigint not null check (file_size > 0 and file_size <= 10485760),
  created_at timestamptz not null default now()
);

create table public.post_likes (
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index posts_created_at_idx on public.posts (created_at desc);
create index posts_author_secret_idx on public.posts (author_id, is_secret);
create index posts_title_search_idx on public.posts using gin (title extensions.gin_trgm_ops);
create index posts_author_name_search_idx on public.posts using gin (author_name extensions.gin_trgm_ops);
create index post_attachments_post_id_idx on public.post_attachments (post_id);
create index post_likes_user_id_idx on public.post_likes (user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_name text;
begin
  new_name := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'name'), ''),
    nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
    '사용자'
  );

  insert into public.profiles (id, display_name)
  values (new.id, left(new_name, 50))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Backfill profiles for users who joined before this migration.
insert into public.profiles (id, display_name)
select
  id,
  left(coalesce(
    nullif(trim(raw_user_meta_data ->> 'name'), ''),
    nullif(split_part(coalesce(email, ''), '@', 1), ''),
    '사용자'
  ), 50)
from auth.users
on conflict (id) do nothing;

create or replace function public.sync_post_like_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.posts set like_count = like_count + 1 where id = new.post_id;
    return new;
  end if;

  update public.posts set like_count = greatest(like_count - 1, 0) where id = old.post_id;
  return old;
end;
$$;

create trigger post_likes_sync_count
after insert or delete on public.post_likes
for each row execute function public.sync_post_like_count();

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_attachments enable row level security;
alter table public.post_likes enable row level security;

create policy "Authenticated users can read profiles"
on public.profiles for select to authenticated
using (true);

create policy "Users can update their own profile"
on public.profiles for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "Users can read public posts and their own secret posts"
on public.posts for select to authenticated
using (not is_secret or author_id = auth.uid());

create policy "Users can read attachments for visible posts"
on public.post_attachments for select to authenticated
using (
  exists (
    select 1 from public.posts p
    where p.id = post_id and (not p.is_secret or p.author_id = auth.uid())
  )
);

create policy "Authors can add attachments to their posts"
on public.post_attachments for insert to authenticated
with check (
  exists (select 1 from public.posts p where p.id = post_id and p.author_id = auth.uid())
);

create policy "Authors can delete their post attachments"
on public.post_attachments for delete to authenticated
using (
  exists (select 1 from public.posts p where p.id = post_id and p.author_id = auth.uid())
);

create policy "Authenticated users can read likes"
on public.post_likes for select to authenticated
using (true);

create policy "Users can like visible posts"
on public.post_likes for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.posts p
    where p.id = post_id and (not p.is_secret or p.author_id = auth.uid())
  )
);

create policy "Users can remove their own likes"
on public.post_likes for delete to authenticated
using (user_id = auth.uid());

-- Posts are written only through these RPCs so password hashing/checking cannot be bypassed.
create or replace function public.create_post(
  p_title text,
  p_content text,
  p_password text,
  p_is_secret boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_id uuid;
  current_name text;
begin
  if auth.uid() is null then raise exception '로그인이 필요합니다.' using errcode = '42501'; end if;
  if char_length(trim(p_title)) not between 1 and 200 then raise exception '제목은 1자 이상 200자 이하여야 합니다.'; end if;
  if char_length(trim(p_content)) < 1 then raise exception '내용을 입력해주세요.'; end if;
  if char_length(p_password) < 4 then raise exception '게시글 비밀번호는 4자 이상이어야 합니다.'; end if;

  select display_name into current_name from public.profiles where id = auth.uid();
  if current_name is null then raise exception '사용자 프로필을 찾을 수 없습니다.'; end if;

  insert into public.posts (author_id, author_name, title, content, password_hash, is_secret)
  values (auth.uid(), current_name, trim(p_title), trim(p_content), crypt(p_password, gen_salt('bf', 10)), coalesce(p_is_secret, false))
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.update_post(
  p_post_id uuid,
  p_title text,
  p_content text,
  p_password text,
  p_is_secret boolean
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if auth.uid() is null then raise exception '로그인이 필요합니다.' using errcode = '42501'; end if;
  if char_length(trim(p_title)) not between 1 and 200 then raise exception '제목은 1자 이상 200자 이하여야 합니다.'; end if;
  if char_length(trim(p_content)) < 1 then raise exception '내용을 입력해주세요.'; end if;

  update public.posts
  set title = trim(p_title), content = trim(p_content), is_secret = coalesce(p_is_secret, false)
  where id = p_post_id
    and author_id = auth.uid()
    and password_hash = crypt(p_password, password_hash);

  if not found then raise exception '게시글 비밀번호가 틀렸거나 수정 권한이 없습니다.' using errcode = '42501'; end if;
end;
$$;

create or replace function public.delete_post(p_post_id uuid, p_password text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if auth.uid() is null then raise exception '로그인이 필요합니다.' using errcode = '42501'; end if;

  delete from public.posts
  where id = p_post_id
    and author_id = auth.uid()
    and password_hash = crypt(p_password, password_hash);

  if not found then raise exception '게시글 비밀번호가 틀렸거나 삭제 권한이 없습니다.' using errcode = '42501'; end if;
end;
$$;

revoke all on public.profiles, public.posts, public.post_attachments, public.post_likes from anon;
revoke all on public.posts from authenticated;
grant select (id, post_number, author_id, author_name, title, content, is_secret, like_count, created_at, updated_at)
on public.posts to authenticated;
grant select, update (display_name) on public.profiles to authenticated;
grant select, insert, delete on public.post_attachments to authenticated;
grant select, insert, delete on public.post_likes to authenticated;
grant usage, select on sequence public.posts_post_number_seq to authenticated;

revoke all on function public.create_post(text, text, text, boolean) from public, anon;
revoke all on function public.update_post(uuid, text, text, text, boolean) from public, anon;
revoke all on function public.delete_post(uuid, text) from public, anon;
grant execute on function public.create_post(text, text, text, boolean) to authenticated;
grant execute on function public.update_post(uuid, text, text, text, boolean) to authenticated;
grant execute on function public.delete_post(uuid, text) to authenticated;

-- Private bucket; access is controlled by storage.objects policies below.
insert into storage.buckets (id, name, public, file_size_limit)
values ('post-attachments', 'post-attachments', false, 10485760)
on conflict (id) do update set public = false, file_size_limit = 10485760;

create policy "Users can upload files under their own post path"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'post-attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
  and (storage.foldername(name))[2] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  and exists (
    select 1 from public.posts p
    where p.id = ((storage.foldername(name))[2])::uuid and p.author_id = auth.uid()
  )
);

create policy "Users can read files attached to visible posts"
on storage.objects for select to authenticated
using (
  bucket_id = 'post-attachments'
  and exists (
    select 1
    from public.post_attachments a
    join public.posts p on p.id = a.post_id
    where a.storage_path = name and (not p.is_secret or p.author_id = auth.uid())
  )
);

create policy "Authors can delete their uploaded files"
on storage.objects for delete to authenticated
using (
  bucket_id = 'post-attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);
